server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 2030502103
    url: jdbc:mysql:///chatgpt?useUnicode=true&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource

# mybatis
mybatis:
  mapper-locations: classpath:cn/edu/gdpu/chatgpt/dao/*.xml
  type-aliases-package: cn.edu.gdpu.chatgpt.domain

#openai
openai:
  key: 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
  hostname: 127.0.0.1
  port: 10809
  timeout: 120
  chatgpt:
    model: gpt-3.5-turbo
    systemRole: You are a helpful assistant

aliyun:
  key: c086e8fb0d7147dca70a883fc4494f55