package cn.edu.gdpu.chatgpt.dao;

import cn.edu.gdpu.chatgpt.domain.User;
import cn.edu.gdpu.chatgpt.domain.UserExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_users
     *
     * @mbggenerated Tue Apr 04 19:27:46 CST 2023
     */
    int countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_users
     *
     * @mbggenerated Tue Apr 04 19:27:46 CST 2023
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_users
     *
     * @mbggenerated Tue Apr 04 19:27:46 CST 2023
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_users
     *
     * @mbggenerated Tue Apr 04 19:27:46 CST 2023
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_users
     *
     * @mbggenerated Tue Apr 04 19:27:46 CST 2023
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_users
     *
     * @mbggenerated Tue Apr 04 19:27:46 CST 2023
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_users
     *
     * @mbggenerated Tue Apr 04 19:27:46 CST 2023
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    User selectById(@Param("id") Integer id);

}